trigger:
- main

jobs:
- job: BuildAndDeploy
  pool:
    vmImage: 'ubuntu-latest'
  dependsOn: []
  steps:
  - task: UseNode@1
    inputs:
      version: '18.x'
  
  - script: |
      npm install
      npm run build
    displayName: 'npm install and build'
    condition: succeeded()

  - task: AzureStaticWebApp@0
    inputs:
      app_location: 'dist'
      output_location: ''
      azure_static_web_apps_api_token: $(deploymentToken)
      skip_app_build: true
      verbose: true
      resourceGroupName: 'LocalLLM'
      connectionType: 'AzureRM'
      azureStaticWebApp: '$(azureResourceId)'
      azureSubscription: 'AzurePersonal'
    condition: succeeded()
